# For more information: https://laravel.com/docs/sail
# Customized by Bc. Jakub Josef Forman
# Tested on Apple Silicon M1 Mac Mini with Docker 3.3.0 (62029) & Docker M1 Preview
version: '3'
services:
  mysql:
    platform: linux/x86_64
    image: 'mysql:8.0'
    restart: always
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'baltaci-test'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'user'
